### ISSUE TITLE
RESEARCH TICKET: determine if catcha api is for front end or backend

### ISSUE THREAD

**Issue by tyannejensen** [skylark-shae/Wandering-Words#26]

**Comment by skylark-shae** [comment]
Adding starter captcha files to frontend and back end. Will need further development.

Repurposing tipAPI file in ./client/src/api/tipAPI.tsx.

**Comment by skylark-shae** [comment]
Basic reCaptcha files added to front and back end. Still needs to be fully implemented and deployed.
